/** @type {import('tailwindcss').Config} */

export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: "class",
	theme: {
		extend: {
			colors: {
				"tertiary-fixed-dim": "#bfc6db",
				"secondary-container": "#42474d",
				"on-surface-variant": "#c5c5da",
				"on-secondary-fixed": "#171c21",
				"on-error": "#690005",
				"surface-container-low": "#191b23",
				"on-tertiary-fixed-variant": "#404758",
				"tertiary-fixed": "#dce2f8",
				"on-tertiary-fixed": "#141b2b",
				"surface-container": "#1d2027",
				"on-primary": "#0010a2",
				"tertiary": "#bfc6db",
				"error-container": "#93000a",
				"secondary-fixed-dim": "#c2c7ce",
				"primary-fixed": "#e0e0ff",
				"on-secondary-fixed-variant": "#42474d",
				"surface-container-lowest": "#0b0e15",
				"surface-container-high": "#272a32",
				"primary": "#bdc2ff",
				"secondary-fixed": "#dfe3ea",
				"on-primary-container": "#cccfff",
				"primary-fixed-dim": "#bdc2ff",
				"on-tertiary-container": "#cbd2e7",
				"on-tertiary": "#293041",
				"on-secondary": "#2c3136",
				"on-error-container": "#ffdad6",
				"surface-variant": "#32353d",
				"surface-tint": "#bdc2ff",
				"secondary": "#c2c7ce",
				"on-primary-fixed": "#000767",
				"surface-dim": "#10131a",
				"on-primary-fixed-variant": "#001be1",
				"outline": "#8f8fa3",
				"on-surface": "#e0e2ec",
				"error": "#ffb4ab",
				"tertiary-container": "#535a6c",
				"on-secondary-container": "#b1b5bc",
				"surface-bright": "#363941",
				"primary-container": "#2337ff",
				"background": "#10131a",
				"inverse-surface": "#e0e2ec",
				"outline-variant": "#444557",
				"inverse-primary": "#2c3fff",
				"surface": "#10131a",
				"surface-container-highest": "#32353d",
				"inverse-on-surface": "#2d3038",
				"on-background": "#e0e2ec"
			},
			fontFamily: {
				"headline": ["Manrope", "sans-serif"],
				"body": ["Inter", "sans-serif"],
				"label": ["Space Grotesk", "sans-serif"]
			},
			borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
		},
	},
}
